#logging:
#  level:
#    root: INFO
#  file:
#    name: logs/app.log
spring:
  application:
    name: EventEase-backend
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:ee-db}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:1234}
    flyway:
      baseline-on-migrate: true
token:
  signing:
    key: 7777777w7w7w7w77w7w7w7w7w77w7ww7w7w7w7w77w7w7w7w77w7w7w7w77w7w7w7w7w
