#logging:
#  level:
#    root: INFO
#  file:
#    name: logs/app.log
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: egorgolovin.7776@gmail.com
    password: cjjasdmmikieiemp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  application:
    name: EventEase-backend
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: true
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:ee-db}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:1234}
    flyway:
      baseline-on-migrate: true
token:
  signing:
    key: 7777777w7w7w7w77w7w7w7w7w77w7ww7w7w7w7w77w7w7w7w77w7w7w7w77w7w7w7w7w
#  spring.mail.host=smtp.gmail.com
#  spring.mail.port=587
#  spring.mail.username= gmail user name
#  spring.mail.password= your password
#  spring.mail.properties.mail.smtp.auth=true
#  spring.mail.properties.mail.smtp.starttls.enable=true